# region standard characters
STANDARD_HORIZONTAL = '─'
STANDARD_VERTICAL = '│'

STANDARD_CORNER_TOP_LEFT = '┌'
STANDARD_CORNER_TOP_RIGHT = '┐'
STANDARD_CORNER_BOTTOM_LEFT = '└'
STANDARD_CORNER_BOTTOM_RIGHT = '┘'

STANDARD_JOIN_CROSS = '┼'
STANDARD_JOIN_LEFT = '├'
STANDARD_JOIN_RIGHT = '┤'
STANDARD_JOIN_TOP = '┬'
STANDARD_JOIN_BOTTOM = '┴'
# endregion standard characters

# region thick characters
THICK_HORIZONTAL = '━'
THICK_VERTICAL = '┃'

THICK_CORNER_TOP_LEFT = '┏'
THICK_CORNER_TOP_RIGHT = '┓'
THICK_CORNER_BOTTOM_LEFT = '┗'
THICK_CORNER_BOTTOM_RIGHT = '┛'

THICK_JOIN_CROSS = '╋'
THICK_JOIN_LEFT = '┣'
THICK_JOIN_RIGHT = '┫'
THICK_JOIN_TOP = '┳'
THICK_JOIN_BOTTOM = '┻'

THICK_STANDARD_JOIN_LEFT = '┠'
THICK_STANDARD_JOIN_RIGHT = '┨'
THICK_STANDARD_JOIN_TOP = '┯'
THICK_STANDARD_JOIN_BOTTOM = '┷'
# endregion thick characters

# region double characters
DOUBLE_HORIZONTAL = '═'
DOUBLE_VERTICAL = '║'

DOUBLE_CORNER_TOP_LEFT = '╔'
DOUBLE_CORNER_TOP_RIGHT = '╗'
DOUBLE_CORNER_BOTTOM_LEFT = '╚'
DOUBLE_CORNER_BOTTOM_RIGHT = '╝'

DOUBLE_JOIN_CROSS = '╬'
DOUBLE_JOIN_LEFT = '╠'
DOUBLE_JOIN_RIGHT = '╣'
DOUBLE_JOIN_TOP = '╦'
DOUBLE_JOIN_BOTTOM = '╩'

DOUBLE_STANDARD_JOIN_LEFT = '╟'
DOUBLE_STANDARD_JOIN_RIGHT = '╢'
DOUBLE_STANDARD_JOIN_TOP = '╤'
DOUBLE_STANDARD_JOIN_BOTTOM = '╧'
# endregion double characters
